# Generated by Django 6.0.3 on 2026-03-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_gender_user_location_user_merchant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller_application_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='seller_status',
            field=models.CharField(choices=[('None', 'No application'), ('Pending', 'Application pending'), ('Approved', 'Seller approved'), ('Rejected', 'Application rejected')], default='None', max_length=20),
        ),
    ]
